### ISSUE TITLE
Request for new feature

### ISSUE THREAD

**Issue by Aztec2012** [Franisz/zUtilities#10]
Hi! Plugin zUtilities is amazing. But what about one new feature? Enable displaying for equipped armors, runes and etc in dead or knocked down NPCs invenory?

**Comment by Franisz** [comment]
Dunno, seems kinda pointless to me. Weapons get unequipped automatically when npc is dead/knocked out. Runes are removed from inventory and all active items like armors can't be selected anyway.

**Comment by Aztec2012** [comment]
Maybe do runes  unequipped automatically when npc is dead/knocked out if its possible.

**Comment by Aztec2012** [comment]
Union needed to works properly on all mods. For armors maybe make function to automatically add armor in inventory when npc is dead/knocked out and after player grab it automatically delete it from body.

**Comment by Franisz** [comment]
Showing equipped items is one thing, giving player ability to loot them is a whole different thing. This is not even close to being a utility feature. Not only it would break the balance, but very possibly break the entire mod!

**Comment by Aztec2012** [comment]
Maybe like MARVIN feature disabled by deafult.

**Comment by Franisz** [comment]
You might as well insert those items through console. I see no point of this, if you need something like that for a specific mod, i already said:
> Runes are automatically removed because of a `B_ClearRuneInv` function from game scripts, it can be simply removed or changed to unequip runes, there is no Union needed for that.

**Comment by Aztec2012** [comment]
Small amount of mods has editable scripts.
