### ISSUE TITLE
Selectable Colored Text

### ISSUE THREAD

**Issue by Marek33** [Franisz/zUtilities#13]
I would love to see a feature, which allows us, to change the selectable text (only selectable text, but not the dialogue one) to any color which user wants. There should be these three lines, **ColorR**=0, **ColorG**=255 and **ColorB**=0.

**Comment by Franisz** [comment]
Added in release [v0.27](../releases/tag/v0.27).

**Comment by pawbuj1981** [comment]
System Pack i tak ma taką opcję.
