### ISSUE TITLE
Pozycje pasków MANA/HP. Nie można zmienic.

### ISSUE THREAD

**Issue by krutki341** [Franisz/zUtilities#14]
Albo ja nie wiem jak to zrobic albo nie dzialaja
Prosze o wytlumaczenie dokladne lub podanie poprawnych pozycji w lewym dolnym ekranie i jak to ustawic

**Comment by Franisz** [comment]
>   - Health, mana and swim status bars position can be changed with `HealthBarPos`, `ManaBarPos` and `SwimBarPos` options.
    - Four positions need to be defined in a form `x1|y1|x2|y2` that reflects a virtual position in `0|0|8192|8192` scope.
    - Default health bar position for systempack `Scale=1` is: `43|7873|1122|8085` and for `Scale=0`: `43|7964|811|8116`
    - Default mana bar position for systempack `Scale=1` is: `7053|7873|8132|8085` and for `Scale=0`: `7381|7964|8149|8116`
    - Default swim bar position for systempack `Scale=1` is: `3556|7873|4635|8085` and for `Scale=0`: `3712|7964|4480|8116`
    - Leave options empty to use default positions.
![Screenshot_3](https://user-images.githubusercontent.com/47374092/178472277-f9006c15-96ab-4f1f-8383-2af382b2753b.png)
 
 #### Eg.:
 ```
 HealthBarPos=43|7964|811|8116
 ManaBarPos=43|7762|811|7914
 ```

**Comment by krutki341** [comment]
Niestety ustawilem sobie pozycje  tak jak opisales z moimi cyframi i nadal mam paski HP z lewej i Many z prawej
