### ISSUE TITLE
Enemies that are locked on using the Lock Target button in Gothic 2 aren't affected by "ColorNpcs" option and others

### ISSUE THREAD

**Issue by thekovic** [Franisz/zUtilities#16]
As you can see in the images, the locked on enemy lacks the colored name and doesn't display the exact health in the health bar.

Maybe this is by design, in that case disregard.

Not locked:
![image](https://user-images.githubusercontent.com/72971433/187994430-9ce7e39c-3f25-43f7-b88f-d4524de68dfc.png)

Locked:
![image](https://user-images.githubusercontent.com/72971433/187994486-f661bd76-0129-4d5e-aab6-998ffaf5b3cd.png)

**Comment by Franisz** [comment]
This is not intended and will be fixed in next release.
