### ISSUE TITLE
Bottom 6 Slots not used for Quick slots not used

### ISSUE THREAD

**Issue by GregorHse** [Franisz/zUtilities#21]
Whenever i quicksave it only overrides the last saveslot. Tried using alternative mode, but it doesnt change anything.

And not an issue but i could not find any info about it: What is the difference between alternative and standard Quick save mode?

My ini:
```
...
QuickSaveMode=2
; ... specifies QuickSave mode, (0) - 'Disabled', (1) - 'Standard', (2) - 'Alternative'
; ... QuickSave with [F10] and QuickLoad with [F12]

KeyQuickSave=KEY_F4
; ... key for QuickSave

KeyQuickLoad=KEY_F6
; ... key for QuickLoad

MinSaveSlot=15
; ... defines min range of used save slots

MaxSaveSlot=20
; ... defines max range of used save slots
...
```

**Comment by Franisz** [comment]
G2 has 20 save slots available but for some reason some mods reduced save slots amount (in game menu) to 15. Not visible slots still function perfectly fine, but you can't see them, so I suggest to change min and max settings from 15-20 to 10-15.

Short description of alternative quicksave mode is [here](https://github.com/Franisz/zUtilities/releases/tag/v0.29).

**Comment by GregorHse** [comment]
Hey, thanks for the fast response. You were right, my mod (Archolos) only has 15 Saveslots. Changed it, and now it works.
