### ISSUE TITLE
UseTimeMultplier does not affect game speed in G2:CoM

### ISSUE THREAD

**Issue by ciahciach** [Franisz/zUtilities#28]
UseTimeMultiplier does not affect game speed despit that the chosen speed is correctly shown in left top corner of the screen by the clock when pressing "Z" key.

**Comment by Franisz** [comment]
You need to enable this feature via game menu or `gothic.ini`. It's disabled by default.

**Comment by ciahciach** [comment]
Yes, I have set the UseTimeMultiplier=1 in gothic.ini, the same is in the in-game menu - it is showing as set to "on"

**Comment by ciahciach** [comment]
EDIT: So sorry, for anyone looking for solution in the future: turns out it is not compatible with NaturalSprint plugin, simply removing it allow the TimeMultiplier to work correctly.
