### ISSUE TITLE
Ukrywanie paska many

### ISSUE THREAD

**Issue by wojtulace** [Franisz/zUtilities#29]
Czy dałoby się zaimplementować taką funkcję, która ukrywa pasek many, gdy bohater nie trzyma czaru?  Wiem, że już jest w Union, ale mi nie działa. Mam podobną na ukrywanie HP i sprawdza się wyśmienicie.

**Comment by Franisz** [comment]
Nie ma sensu dodawać istniejących już funkcjonalności. Wystarczy ustawić `ShowManaBar = 1` w `SystemPack.ini`.

**Comment by wojtulace** [comment]
Nie wystarczy ponieważ nie działa. I to sprawa moda L'hiver bo w zwykłym NK działa. Ciekawe dlaczego.

**Comment by Franisz** [comment]
W takim razie jest to problem moda a nie ustawienia. Plik ini moda może nadpisywać poszczególne ustawienia, ale może też sam mod z jakiegoś powodu zmieniać działanie pasków.

**Comment by wojtulace** [comment]
W pliku ini moda nic nie ma ciekawego, więc jestem uziemiony. W każdym razie wasz mod jest super. Uważam, że ma wiele pomocnych funkcji.

**Comment by Franisz** [comment]
Nie wiem, którą wersję L'Hivera masz na myśli, ale obstawiam, że te niemieckie, które korzystają z ikarusa, mogą ingerować w działanie pasków statusu, więc pytał bym autorów na jakimś forum czy gdzieś.
