### ISSUE TITLE
slow/long shutdown of Gothic I/II

### ISSUE THREAD

**Issue by wahoonie76** [Franisz/zUtilities#4]
Hi,

at first: big THANKS for your great patch/plugin - I love all the new functions and options.

I used it on Gothic I Classic also on Gothic II NotR and the zUtilities **0.12** causes a long shutdown of the game: it took a while before I can use other programs normally (**Gothic I:** the mouse is seen in Windows 10 this time but I can not use the GothicStarter.exe again while the game is closing; **Gothic II:** the mouse is not seen in Windows 10 this time, bit I can switch to other running programs and use them with keyboard). I tried this with all other patches I installed seperatly and there is no such behavior, only if zUtilities 0.12 is activated, also if it is the only used patch.

Nothing of this happens if I use an earlier Version of this plugin.

Thanks for your answer in advance.

Greetings

wahoonie76

**Comment by wahoonie76** [comment]
it works perfect now, both on Gothic 1 and 2.

I didn't find a button to write an comment on your plugin - not an issue. So I will try to do it here: 
Is is possible to use the Quicksave-function for each installed mod. So that your plugin takes the values for last saved game and last used number from the **iLastSaceSlot**_**ModName**_ and **iLastSaveNumer**_**ModName**_-variables?
LHaart has also an Union-Patch which implements a Quicksave-functions and others ([@rpgrussia.com](https://rpgrussia.com/resources/poleznye-funkcii-quickloot-quicksave-hotbar-i-prochee-g1-i-mody.626/)) - I asked him before ([my question](https://rpgrussia.com/threads/poleznye-funkcii-quickloot-quicksave-hotbar-i-prochee-g1-i-mody.23398/page-32#post-542918)) and he wrote that is not possible ([his comment](https://rpgrussia.com/threads/poleznye-funkcii-quickloot-quicksave-hotbar-i-prochee-g1-i-mody.23398/page-33#post-542923)] but I don't know if he means it in generally for Union or for his own plugin.
Maybe you know a solution or have an idea. Otherwise I had to put a section of the 2 variables to Gothic.ini for each mod and comment out the not used (set or delete the ";"):
```[ZUTILITIES]
[..]
; QuickSave for unmodded --> (un)comment if change playing mod
sSaveName=QuickSave_
iMinSaveSlot=10
iMaxSaveSlot=15
iLastSaveSlot=11
iLastSaveNumber=56
; QuickSave for Mod Name_1 --> (un)comment if change playing mod
sSaveName=QuickSave_Name_1
iMinSaveSlot=10
iMaxSaveSlot=15
iLastSaveSlot=15
iLastSaveNumber=8
; QuickSave for Mod Name_2 --> (un)comment if change playing mod
;sSaveName=QuickSave_Name_2
;iMinSaveSlot=10
;iMaxSaveSlot=15
;iLastSaveSlot=
;iLastSaveNumber=
[..]
```

So again: I like your plugin very much - excellent work.

Greetings

wahoonie

**Comment by Franisz** [comment]
Usually you can set override variables in **`.ini` file of the mod** when mod is actually run through gothic starter like so:
```ini
[OVERRIDES]
ZUTILITIES.bRenderInvItems=0
ENGINE.zWindEnabled=1
```
Unfortunately with current quicksaving method of storing `iLastSaveSlot` and `iLastSaveNumber` values, overrides wouldn't do much so in next version I will change that and quicksaves will work automatically and separately for every mod.

**Comment by wahoonie76** [comment]
Perfect!
I put a star on your project.
