### ISSUE TITLE
dodanie modyfikacji kolorów do ini 

### ISSUE THREAD

**Issue by pawbuj1981** [Franisz/zUtilities#6]
Filip czy możesz dodać możliwość edycji kolorów npc, itemów etc. do ini. Zaawansowany user (taki jak ja ) mógłby się tym pobawić .. i ustawić wg uznania....

**Comment by Franisz** [comment]
W pluginie jest za dużo różnych kolorów, żeby umieszczać je w `gothic.ini`. Jeśli chcesz się bawić w jakieś większe zmiany to proponuję zrobić forka.

**Comment by pawbuj1981** [comment]
W sumie tak jest też jest dobrze..(jednej zmiany nie doczytałem.). 

Mam mały pomysł na kolejną zmianę tj . RefuseTalks na wzór z Wiedzimina. Nie ma tam bezsensowej opcji "Koniec" w dialogach. Mam to zrobione dla G1 w pakiecie Ninja (dla G2 pewnie inne adresy,cale to nie jest raczej problem).

Może spodoba ci się ten pomysł..

`/*
 * Hook for B_AssessTalk
 */
func void Ninja_RefuseTalks_B_AssessTalk() {
    var int infoCount; infoCount = Ninja_RefuseTalks_oCInfoManager_GetInfoCount(self, other);

    if (!infoCount) && (self.npcType == npctype_main) {
        B_SayOverlay(self, other, "$NOTNOW");
        return;
    } else if (infoCount == 1) && (self.npcType == npctype_main) {
        var int infoPtr; infoPtr = Ninja_RefuseTalks_oCInfoManager_GetInfo(self, other, 0);

        if (infoPtr) {
            var oCInfo dlgInstance; dlgInstance = _^(infoPtr);
            if (Hlp_StrCmp(dlgInstance.description, Ninja_RefuseTalks_DIALOG_ENDE)) {
                B_SayOverlay(self, other, "$NOTNOW");
                return;
            };
        };
    };

    // Otherwise continue with the underlying B_AssessTalk
    ContinueCall();
};`

**Comment by Franisz** [comment]
Nie wydaje mi się, żeby takie coś było dobrym pomysłem, chociażby dlatego, że część dialogów w condition sprawdza czy npc jest w `ZS_TALK`. Poza tym takie coś można zrobić w skryptach i to nawet bez ikarusa.
