### ISSUE TITLE
Item labels noto be seen with activated Union Advanced-Inventory-Plugin

### ISSUE THREAD

**Issue by wahoonie76** [Franisz/zUtilities#7]
Hey Franisz,

thank you so much for your plugin development.

Actually I have an issue (?) with showing the item labels in opened inventory. It's only if I play with activated Advanced Inventory-Plugin from [Xeдин](https://worldofplayers.ru/threads/42358/post-1128974).

In Gothic I the function of advanced inventory at the moment is only available for players inventory (Screenshot 1), not if you just opened a chest or a NPC (Screenshot 2).

![Gothic 1 Screenshot 1](https://user-images.githubusercontent.com/20705724/141320206-74c95cfd-5fe3-4609-ba08-f1b407d1b5bf.png)
![Gothic 1 Screenshot 2](https://user-images.githubusercontent.com/20705724/141320236-e37c8308-1195-4f0a-9da4-7261689b5574.png)

Maybe it's possible to discuss this with [Xeдин](https://worldofplayers.ru/members/10335/) from the worldofplayers.ru forum (sorry, I'm not a coder). I will also ask him on his [plugins forum thread](https://worldofplayers.ru/threads/42358/post-1128974).

Greetings

wahoonie

**Comment by hedin77** [comment]
I think that need CanDrawLabel  method fix and allow draw other view or make checking by item.

**Comment by Franisz** [comment]
> I think that need CanDrawLabel method fix and allow draw other view or make checking by item.

It is intentionally made so that views that render items but aren't inventory cells don't have labels. Why AdvInventory doesn't use original inventory views?

**Comment by hedin77** [comment]
I used zCViewInteractive instead zView for extend functionality of view and not used original inventory views of item.

**Comment by Franisz** [comment]
I released new version that should fix this problem.

**Comment by hedin77** [comment]
It worked, thanks.
![image](https://user-images.githubusercontent.com/11011535/141425340-5c840dce-07ed-4ff0-a99e-f212d89414dd.png)
