### ISSUE TITLE
zmiany przy wpisach do dziennika przy zadaniach

### ISSUE THREAD

**Issue by pawbuj1981** [Franisz/zUtilities#8]
W wielu modach (szczególnie tych starszych) brakuje "fjuczerów" odnośnie wpisu do dziennika .

O ile dodanie nazwy zadania przy każdym kolejnym wpisie do dziennika nie jest problemem za pomocą zwykłych skryptów to wpis typu "Nowe zadanie : ( Przyjęcie do Starego Obozu)" wymaga bodajże Ikarusa. 

Może to dodać warto to dodać .. dodaje to smaku w trakcie gry. 
Wyświetlanie statusu zadania przy jego rozpoczęciu bądź zakończeniu mogłoby być w innym kolorze (np. na wzór "Z życia Złodzieja" czy "Dark Saga"). 
Będę wdzięczny za wzięcie pod uwagę przy kolejnym update.

EDIT1: Jeszcze jedna rzecz mi się przypomniała. Handel w G1 jest trochę toporny...żeby przespieszyć transakcję można by np. ENTERem dokładać brakującą ilość rudy po każdej ze stron. 

EDIT2: Przy wyświetlaniu zadawanych obrażeń nie widzę róznicy po trafieniu krytycznym (może warto to określić innym kolorem np. yellow).

**Comment by Franisz** [comment]
Zamykanie się wpisów w dzienniku jest upośledzone po stronie skryptów i tak czy siak tam trzeba by to zmieniać. Tak naprawdę wystarczy jeden external na pobranie statusu topica i już można zrobić fajny system wpisów.

Raczej nie planuję robić ekskluzywnych dla G1 ficzerów więc handlu raczej nie zmienię.

Przy trafieniu krytycznym na domyślnych ustawieniach popup powinien być czerwony i większy. Testowałem na kilku modach co zmieniają trochę liczenie obrażeń i nie zauważyłem żadnych problemów.

Na przyszłość zakładaj osobne issue dla różnych rzeczy :)

**Comment by pawbuj1981** [comment]
Dzięki za odp. i podpowiedź :) - nie chciałem tworzyć za dużo wątków.

Rozumiem, że nie będziesz jednak edytował "podstawowego" systemu wpisów ..no szkoda.
