### ISSUE TITLE
zmiana pozycji boxów dialogowych 

### ISSUE THREAD

**Issue by pawbuj1981** [Franisz/zUtilities#9]
Filip 

czy możesz dodać podobnie na wzór przemieszczenia pasków opcje przesuwania boxów dialogowych (choice box, ew. inne) ? Fajnie by było mieć możliwość zmiany tych pozycji.

**Comment by Franisz** [comment]
Dawanie tutaj dowolności nie wydaje mi się dobrym pomysłem. Dodam może jakiś alternatywny preset.

**Comment by pawbuj1981** [comment]
Robiłem to kiedyś ikarusem. Proponuję 2 opcje:

1) choice box po lewej stronie i nieco wyżej (coś na wzór Wiedżmina 3);
2) choice box nieco wyżej tak aby widoczna była dolna krawędź boxa; 

Inne to nie ma sensu , przecież nie zrobimy tego na samym środku ekranu albo na górze...:)

**Comment by Franisz** [comment]
Z tego co pamiętam to w wiedźminie 3 były opcje dialogowe po prawej stronie, i na dodatek były one bardzo krótkie. W gothicu, szczególnie na większej skali, mogą teksty wychodzić i za boxa i inne cyrki się dziać.
Tutaj jakiś wariant, na całą szerokość ekranu, i dodatkowo opcje wycentrowane w poziomie i w pionie.
![Screenshot_3](https://user-images.githubusercontent.com/47374092/147754395-a7084a18-6863-46a6-b867-69079c2e8c0f.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/47374092/147754465-a278e8e8-843f-424d-93f8-b70485440d87.jpg)
Z oryginalnymi teksturami i animowanymi oknami wygląda w sumie nieźle, gorzej trochę gdy te rzeczy są zmienione.

**Comment by pawbuj1981** [comment]
Wygląda to prawie jak cinemascope. Moim skromnym zdaniem super funkcjonalność.

**Comment by pawbuj1981** [comment]
Tak to wyglądało w moim starym modzie (jest to trochę za wysoko). Niestety na pakiecie ninja ten kod nie działa.
![choice box fix a](https://user-images.githubusercontent.com/62994611/147821237-f3b43f94-cdf8-4c85-b025-19ba167eff90.jpg)

**Comment by pawbuj1981** [comment]
Ok ogarnąłem temat dzięki Lego i dodałem już jako paczkę vdf. Kod poniżej (może się przyda).
Natomiast podtrzymuję pomysł z cinemascope. Do g2 jest taka paczka (niestety nie działa pod g1). 

`func void SetChoiceBoxScale ()
{
    var int ptr; ptr = MEM_ReadInt(MEMINT_oCInformationManager_Address+28);
    
    MEM_WriteInt (ptr+64, STR_ToInt (MEM_GetGothOpt ("VIDEO", "zVidResFullscreenY"))); 
    Print_GetScreenSize(); //Pobiera rozdzielczość ekranu  
    //if ((STR_ToInt(MEM_GetModOpt("UPDATE_PACK", "Dialog_position_enabled"))))//
    //{  
	//MEM_WriteInt (ptr+60, 620);//os x       
    //MEM_WriteInt (ptr+56, 120);//oś y  //było 120   
     
    //HookEngineF (7337648, 6, HookSVM);
   // HookSVM();
   MEM_WriteInt (ptr+60, 820);//os x       
    MEM_WriteInt (ptr+56, 120);//oś y  //było 120   
   //};
};`
